// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package users

import (
	"star/api/users"
	userLogic "star/internal/logic/users"
)

type ControllerV1 struct {
	users *userLogic.Users
}

func NewV11() users.IUsersV1 {
	print(1111)
	return &ControllerV1{
		users: userLogic.New(),
	}
}
func NewV22() users.IUsersV1 {
	print(1111)
	return &ControllerV1{
		users: userLogic.New(),
	}
}
