// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"star/internal/dao/internal"
)

// usersInfoDao is the data access object for the table users_info.
// You can define custom methods on it to extend its functionality as needed.
type usersInfoDao struct {
	*internal.UsersInfoDao
}

var (
	// UsersInfo is a globally accessible object for table users_info operations.
	UsersInfo = usersInfoDao{internal.NewUsersInfoDao()}
)

// Add your custom methods and functionality below.
